apiVersion: v1
kind: Service
metadata:
  name: one-docs
  labels:
    app: one-docs
    app.kubernetes.io/name: one-docs
spec:
  type: ClusterIP
  selector:
    app: one-docs
  ports:
    - name: http
      port: 80
      targetPort: 8090
      protocol: TCP
